module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond',
    'Gerudo',
    'Nebula',
    'Titan',
    'Mustafar',
    'Cybertron',
    'Faron',
    'Eldin',
    'Lanayru',
    'Crystal',
    "Griffin's",
    'Midna',
    'Smokey',
    'Oak',
    'Skull',
    'Greyskull',
    'Voorhees',
    "Godric's",
    'Tattooine',
    'Shatterback',
    'Lon-Lon',
    'Shadow',
    'Rito',
    'Hebra',
    'Woodland',
    'Akkala',
    'Necluda',
    'Tabantha',
    'Kakariko'
]

module.exports.places = [
    'Flats',
    'Village',
    'Canyon',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Ghost Town',
    'Camp',
    'Dispersed Camp',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Springs',
    'Bayshore',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
    'Hollow',
    'Valley',
    'Lake',
    'Bay',
    'Isle',
    'Lodge',
    'Straights',
    'Lands',
    'State Park',
    'Rocks',
    'National Park',
    'National Forest',
    'Falls',
    'Woods',
    'Cove',
    'Landing',
    'Forest',
    'Hills',
    'Basin',
    'Canyon',
    'Rock',
    'Plains',
    'Ridge',
    'Meadow',
    'Pointe',
    'Ranch',
    'Prarie',
    'Wetlands',
    'Grasslands',
    'Highlands',
    'Mountain',
    'Fields'
]

